In [5]:
import pandas as pd
import numpy as np
import os
os.chdir(r'D:\Git\Git\pandasProject\Data')

#解决中文显示问题，下面的代码只需运行一次即可
import matplotlib as plt
plt.rcParams['font.sans-serif'] = ['SimHei']
plt.rcParams['axes.unicode_minus'] = False
from sqlalchemy import create_engine # 导入引擎对象

# 1.Pandas操作csv文件

In [8]:
# 1. 读取csv文件，获取数据
# 参数解释：参数1：文件路径，参数2：分隔符，参数3：指定列
df = pd.read_csv('./../Data/stock_data.csv', sep=',',usecols=['open','high','low','close','volume']) # 默认使用,分隔符，获取数据指定列
df

      open   high  close    low  volume
0    23.75  25.03  21.03  23.41  604263
1    29.51  29.68  29.03  28.95  500126
2    27.32  27.64  25.05  26.97  552329
3    25.99  27.79  28.26  25.81  527632
4    21.56  22.77  23.20  21.32  696382
..     ...    ...    ...    ...     ...
195  23.49  25.35  24.74  21.75  599608
196  27.26  28.98  26.68  25.40  560774
197  28.97  29.83  21.72  27.84  523752
198  28.87  30.37  21.92  27.48  555029
199  27.80  29.31  20.41  25.96  648757

[200 rows x 5 columns]

In [17]:
# 2.把读取的数据，写到文件中
df[:10].to_csv('./../Data/my_file1.csv',sep=',',index=False) # index=False表示不写入索引列
print("写入成功！")

写入成功！

In [18]:
# 3.特殊的csv文件 ---> tsv文件
# 区别：csv文件 --> 以 ， 做分隔    tsv文件 --> 以  \t （tab键）做分隔
df[:5].to_csv('./../Data/my_file2.csv',sep='\t',index=False) # index=False表示不写入索引列
print("写入成功！")

写入成功！

In [21]:
# 4.读取tsv文件
# 参数解释：参数1：文件路径，参数2：分隔符，参数3：指定索引列
df2 = pd.read_csv('./../Data/my_file2.csv',sep='\t',index_col=0)
df2

        high  close    low  volume
open
23.75  25.03  21.03  23.41  604263
29.51  29.68  29.03  28.95  500126
27.32  27.64  25.05  26.97  552329
25.99  27.79  28.26  25.81  527632
21.56  22.77  23.20  21.32  696382

# 2.Panndas操作Mysql数据表

In [1]:
# 前提：Anaconda已经装入 pymysql 和 sqlalchemy 模块
# 安装方式：pip install pymysql
# 安装方式：pip install sqlalchemy
# 此外还要装入 mysql数据库

In [25]:
# 需求：把数据写入MySQL数据库表中
# 1.准备写到mysql数据表 的数据
data = pd.read_csv('./../Data/cvs文件.cvs',encoding='utf-8',index_col=0)
data

     birthday name   AKA
0
1    1960/5/7  刘海柱  职业法师
2    1978/9/1  赵金龙   大力哥
3  1984/12/27  周立齐  窃格瓦拉
4   1969/1/24   于谦  相声皇后

In [15]:
# 2.导包
# from sqlalchemy import create_engine # 导入引擎对象

In [23]:
# 3.创建引擎对象
# 参数解释：参数1：数据库类型+数据库驱动名://用户名:密码@数据库地址:端口号/数据库名?编码方式
engine = create_engine('mysql+pymysql://root:123456@localhost:3306/python?charset=utf8')

# # 4.具体向数据路中写入数据
# # 参数解释：参数1：数据表名，参数2：引擎对象，参数3：是否把索引列写入数据表，参数4：如果数据表存在 如何处理
data.to_sql('my_table1',engine,index=False,if_exists='append')
print("写入成功！")

写入成功！

In [26]:
# 6.从sql表中读取数据、
sql_df =pd.read_sql('my_table1',engine)
sql_df =pd.read_sql('select name,AkA from my_table1 limit 0,2',engine)
sql_df

  name   AKA
0  刘海柱  职业法师
1  赵金龙   大力哥