In [ ]:
from idlelib.iomenu import encoding

import pandas as pd
import numpy as np
import os
os.chdir(r'D:\Git\Git\pandasProject\Data')

#解决中文显示问题，下面的代码只需运行一次即可
import matplotlib as plt
plt.rcParams['font.sans-serif'] = ['SimHei']
plt.rcParams['axes.unicode_minus'] = False
from sqlalchemy import create_engine # 导入引擎对象

# 1.Pandas增删改查操作 --> 增

In [ ]:
# 1.准备数据
df = pd.read_csv('./../Data/全球GDP数据.csv', encoding='utf-8')
df

In [ ]:
# 2.从原始数据集中，拷贝一部分出来，做操作
df_new = df[:5].copy()
df_new

In [ ]:
# 3.新增列
# 思路1：通过直接赋值的方式 新增1列
df_new['c1'] = 66   # 固定写法
df_new['c2'] = ['12','23','哈哈哈','ae','3']  # 传入列表
df_new['c3'] = df_new.year * 2  # 通过已有列（Series对象）计算

def fun1():
    return '88888'

df_new['c4'] = fun1()
df_new

In [ ]:
# 思路2：通过DataFrame对象.assign()方法 新增1列
df3 = df[:5].copy()
df3

In [ ]:
df3.assign(
    c1 = 66,
    c2 = ['12','23','哈哈哈','ae','3'],
    c3 = df3.year * 2,
    c4 = fun1()
)

# 1.Pandas增删改查操作 --> 删、去重

In [ ]:
# 1.准备数据
df4 = df[:10].copy()
df4

In [ ]:
# 2.删除行 drop()函数 ，除非指定inplace=True，否则不会修改原数据
# df4.drop(index=[0,2,4])  # 不会修改原数据
df4.drop(index=[0], inplace=True) #会修改元数据

df4

In [ ]:
# 3.删除列 --> del 关键字，会直接修改原数据
del df4['year']  #删除year列

df4

In [ ]:
# 4.删除列  --> drop()函数
df4.drop(columns=['year'], inplace=True)
df4

In [ ]:
# 5.去重
# 场景1： DataFrame去重  ———> 以行为单位比较
df5 = df[:5].copy()

# 拼接df5 和 df5 -->组合成有重复的DataFrame
df6 = pd.concat([df5,df5])
df6

# DataFrame去重
df6.drop_duplicates() #如果设置inplace=True，则会修改原数据
df6

In [ ]:
#场景2： Series去重  ———> 以列为单位比较
df6.country.drop_duplicates()
df.country.drop_duplicates()

In [10]:
# 1.准备数据
df7= df[:5].copy()
df7

   year country           GDP
0  1960      美国  543300000000
1  1960      英国   73233967692
2  1960      法国   62225478000
3  1960      中国   59716467625
4  1960      日本   44307342950

In [12]:
df7['c1'] = 23
df7

   year country           GDP  c1
0  1960      美国  543300000000  23
1  1960      英国   73233967692  23
2  1960      法国   62225478000  23
3  1960      中国   59716467625  23
4  1960      日本   44307342950  23

In [16]:
# 修改GDP的值
df7['GDP'] = [1,2,1,88888888,-250] # 直接修改原
# 数据
df7

   year country       GDP  c1
0  1960      美国         1  23
1  1960      英国         2  23
2  1960      法国         1  23
3  1960      中国  88888888  23
4  1960      日本      -250  23

In [19]:
# 4.采用replace()替换

#美国 ---> usa
df7.country.replace('美国','usa')

0    usa
1     英国
2     法国
3     中国
4     日本
Name: country, dtype: object

In [21]:
# 4.Pandas的增删改查操作  -> 差 和 排序
df

     year country             GDP
0    1960      美国    543300000000
1    1960      英国     73233967692
2    1960      法国     62225478000
3    1960      中国     59716467625
4    1960      日本     44307342950
..    ...     ...             ...
415  2019      法国    583225478000
416  2019      中国  14342716467625
417  2019      日本   5082307342950
418  2019     加拿大    524461721692
419  2019     意大利    544385288344

[420 rows x 3 columns]

In [ ]:
# 2.获取前5条数据
df.head(5)
df.head()   # 默认5条

In [24]:
# 3.获取最后5条数据
df.tail(3)

     year country            GDP
417  2019      日本  5082307342950
418  2019     加拿大   524461721692
419  2019     意大利   544385288344

In [28]:
# 4根据列名获取数据
df['year']  # 获取year列  -> Series对象
df.year  # 获取year列  -> Series对象
df[['year']] # 获取year列  -> DataFrame对象

df[['year','country']] # 获取year列 和 country列  -> DataFrame对象

     year country
0    1960      美国
1    1960      英国
2    1960      法国
3    1960      中国
4    1960      日本
..    ...     ...
415  2019      法国
416  2019      中国
417  2019      日本
418  2019     加拿大
419  2019     意大利

[420 rows x 2 columns]

In [29]:
# 5.根据行索引值来获取数据
df[:5]  # 获取前5行
df[1:5:2] # 获取1 , 3行，包左不包右
df[10::5] # 从10开始，到末尾结束，步长为5

     year country             GDP
10   1961      中国     62716467625
15   1962      英国     79233967692
20   1962     意大利     46385288344
25   1963      日本     53307342950
30   1964      法国     74225478000
..    ...     ...             ...
395  2016      中国  11191716467625
400  2017      英国    546233967692
405  2017     意大利    526385288344
410  2018      日本   4954307342950
415  2019      法国    583225478000

[82 rows x 3 columns]

In [34]:
# 6.通过query()函数，结合条件获取
# 需求：查询中美日三国 2015 ~ 2019年的数据
df.query('country in ["中国","美国","日本"] and year in [2015,2016,2017,2018,2019]')
df.query('country in ["中国","美国","日本"] and (year >= 2015 and year <= 2019)')

     year country             GDP
385  2015      美国  18243300000000
388  2015      中国  11061716467625
389  2015      日本   4389307342950
392  2016      美国  18753300000000
395  2016      中国  11191716467625
396  2016      日本   4926307342950
399  2017      美国  19523300000000
402  2017      中国  12143716467625
403  2017      日本   4867307342950
406  2018      美国  20583300000000
409  2018      中国  13608716467625
410  2018      日本   4954307342950
413  2019      美国  21433300000000
416  2019      中国  14342716467625
417  2019      日本   5082307342950

In [36]:
# 7. 排序
df.sort_index(ascending=False) #根据 行索引值排序，降序

     year country             GDP
419  2019     意大利    544385288344
418  2019     加拿大    524461721692
417  2019      日本   5082307342950
416  2019      中国  14342716467625
415  2019      法国    583225478000
..    ...     ...             ...
4    1960      日本     44307342950
3    1960      中国     59716467625
2    1960      法国     62225478000
1    1960      英国     73233967692
0    1960      美国    543300000000

[420 rows x 3 columns]

In [38]:
# 根据内容，例如：year降序，一直就根据GDP降序
df.sort_values(['year','GDP'], ascending=False)
# 根据year降序，一致就根据GDP升序

df.sort_values(['year','GDP'], ascending=[False,True])

     year country            GDP
418  2019     加拿大   524461721692
419  2019     意大利   544385288344
414  2019      英国   564233967692
415  2019      法国   583225478000
417  2019      日本  5082307342950
..    ...     ...            ...
4    1960      日本    44307342950
3    1960      中国    59716467625
2    1960      法国    62225478000
1    1960      英国    73233967692
0    1960      美国   543300000000

[420 rows x 3 columns]

In [43]:
# 8. rank()，类似于SQL的窗口函数
df8 = pd.DataFrame({
    '姓名':['小明','小美','小强','小兰'],
    '成绩':[100,90,90,70]
})
df8

   姓名   成绩
0  小明  100
1  小美   90
2  小强   90
3  小兰   70

In [47]:
df8['成绩排名_min'] = df8.成绩.rank(method='min',ascending=False)
df8['成绩排名_max'] = df8.成绩.rank(method='max',ascending=False)
df8['成绩排名_dense'] = df8.成绩.rank(method='dense',ascending=False)
df8['成绩排名_avg'] = df8.成绩.rank(method='average',ascending=False)
df8['成绩排名_默认'] = df8.成绩.rank(ascending=False)
df8

   姓名   成绩  成绩排名_min  成绩排名_max  成绩排名_dense  成绩排名_avg  成绩排名_默认
0  小明  100       1.0       1.0         1.0       1.0      1.0
1  小美   90       2.0       3.0         2.0       2.5      2.5
2  小强   90       2.0       3.0         2.0       2.5      2.5
3  小兰   70       4.0       4.0         3.0       4.0      4.0