In [1]:
from idlelib.iomenu import encoding

import pandas as pd
import numpy as np
import os

from pandas import pivot_table

os.chdir(r'D:\Git\Git\pandasProject\Data')

#解决中文显示问题，下面的代码只需运行一次即可
import matplotlib as plt
plt.rcParams['font.sans-serif'] = ['SimHei']
plt.rcParams['axes.unicode_minus'] = False
from sqlalchemy import create_engine # 导入引擎对象

# 1.Pandas进阶语法_缺失值处理

## 1.1 思路1：删除缺失值

In [2]:
# 1.读取数据
movie_df = pd.read_csv('./../Data/movie_data.csv')
movie_df

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Proactive 5thgeneration infrastructure,Action,Gas modern statement production position class...,Ethan Oliver,"Kayla Graham, Austin Flores",2006,114,NaN,41007.0,696.77,42.9
1,2,Networked asymmetric middleware,Romance,Base describe voice especially fast lay art bl...,Cristina Garcia,"Kaitlyn Nelson, Kevin Shaw",1988,123,5.2,172732.0,NaN,64.1
2,3,Decentralized composite conglomeration,Comedy,Human born the. Field clear option artist gove...,Kevin Adams,"Daniel Guerra, Zachary Clark, Mark Lee",1984,80,8.0,950379.0,NaN,53.8
3,4,Secured global budgetary management,Drama,Present scene itself pass. Officer mission tra...,Deborah Hernandez,"Crystal Gonzalez, Nicole Vargas, Brandon Glass",2007,153,9.4,39528.0,685.14,58.5
4,5,Progressive 24hour migration,Adventure,Price authority nice quality. Help magazine ge...,Bryan Shaw,"Brandi Smith, Jeffrey Turner, Andrew Wilson, A...",2020,147,6.2,14157.0,343.83,78.3
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Automated holistic neural-net,Sci-Fi,Let market herself then start threat. Nation f...,Brittany Parrish,"Linda White, Sarah Foley",1994,80,9.3,915923.0,18.75,30.4
996,997,Distributed upward-trending attitude,Action,Back sell still green drive. Sound whether tea...,Cameron Mullins,"Charles Frost, Ashlee Wagner, Austin Rodriguez...",1983,171,8.8,589826.0,678.87,41.8
997,998,Pre-emptive zero tolerance intranet,Thriller,Film realize indeed land after to wide. Dark a...,Joshua Glover,"Jason Morales MD, Deanna Smith, Logan Hardy",1994,164,6.4,736854.0,112.06,22.3
998,999,Universal client-server moderator,Drama,Like probably shoulder other. Skill adult admi...,Robert Ramos,"Samantha Carlson, Sabrina Jones, Candace Walker",1990,103,8.0,898654.0,724.35,75.5
999,1000,Operative secondary toolset,Action,Professional most offer recent. Threat million...,Bruce Myers,"Frank Holmes, Samantha Cabrera",2008,88,8.9,258600.0,287.35,NaN

In [3]:
# 2. 查看数据介绍
movie_df.columns  # 查看所有的列名
movie_df.info()   # 查看数据的 基本信息（列名、数据类型、非缺失值的数量等）
movie_df.describe() # 查看数据的 描述性统计信息

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Rank                1000 non-null   int64
 1   Title               1000 non-null   object
 2   Genre               1000 non-null   object
 3   Description         1000 non-null   object
 4   Director            1000 non-null   object
 5   Actors              1000 non-null   object
 6   Year                1000 non-null   int64
 7   Runtime (Minutes)   1000 non-null   int64
 8   Rating              856 non-null    float64
 9   Votes               905 non-null    float64
 10  Revenue (Millions)  818 non-null    float64
 11  Metascore           848 non-null    float64
dtypes: float64(4), int64(3), object(5)
memory usage: 93.9+ KB

,Rank,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
count,1000.000000,1000.000000,1000.00000,856.000000,905.000000,818.000000,848.000000
mean,500.500000,2002.002000,129.19000,6.717640,511128.537017,502.912689,59.428892
std,288.819436,12.719347,29.88714,1.616148,287312.468917,300.109165,22.704128
min,1.000000,1980.000000,80.00000,4.000000,2964.000000,1.080000,20.000000
25%,250.750000,1992.000000,103.00000,5.300000,268039.000000,226.915000,40.100000
50%,500.500000,2002.000000,129.00000,6.700000,522816.000000,508.030000,59.050000
75%,750.250000,2013.000000,155.00000,8.100000,754631.000000,760.410000,77.825000
max,1000.000000,2024.000000,180.00000,9.500000,998251.000000,999.470000,100.000000

In [4]:
# 3.
movie_df.dropna() # 删除所有有缺失值的行，不会修改原数据，加入参数inplace=True即可，默认axis=0 是行，axis=1 是列
movie_df.dropna(axis=1) # 删除所有有缺失值的列
movie_df

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Proactive 5thgeneration infrastructure,Action,Gas modern statement production position class...,Ethan Oliver,"Kayla Graham, Austin Flores",2006,114,NaN,41007.0,696.77,42.9
1,2,Networked asymmetric middleware,Romance,Base describe voice especially fast lay art bl...,Cristina Garcia,"Kaitlyn Nelson, Kevin Shaw",1988,123,5.2,172732.0,NaN,64.1
2,3,Decentralized composite conglomeration,Comedy,Human born the. Field clear option artist gove...,Kevin Adams,"Daniel Guerra, Zachary Clark, Mark Lee",1984,80,8.0,950379.0,NaN,53.8
3,4,Secured global budgetary management,Drama,Present scene itself pass. Officer mission tra...,Deborah Hernandez,"Crystal Gonzalez, Nicole Vargas, Brandon Glass",2007,153,9.4,39528.0,685.14,58.5
4,5,Progressive 24hour migration,Adventure,Price authority nice quality. Help magazine ge...,Bryan Shaw,"Brandi Smith, Jeffrey Turner, Andrew Wilson, A...",2020,147,6.2,14157.0,343.83,78.3
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Automated holistic neural-net,Sci-Fi,Let market herself then start threat. Nation f...,Brittany Parrish,"Linda White, Sarah Foley",1994,80,9.3,915923.0,18.75,30.4
996,997,Distributed upward-trending attitude,Action,Back sell still green drive. Sound whether tea...,Cameron Mullins,"Charles Frost, Ashlee Wagner, Austin Rodriguez...",1983,171,8.8,589826.0,678.87,41.8
997,998,Pre-emptive zero tolerance intranet,Thriller,Film realize indeed land after to wide. Dark a...,Joshua Glover,"Jason Morales MD, Deanna Smith, Logan Hardy",1994,164,6.4,736854.0,112.06,22.3
998,999,Universal client-server moderator,Drama,Like probably shoulder other. Skill adult admi...,Robert Ramos,"Samantha Carlson, Sabrina Jones, Candace Walker",1990,103,8.0,898654.0,724.35,75.5
999,1000,Operative secondary toolset,Action,Professional most offer recent. Threat million...,Bruce Myers,"Frank Holmes, Samantha Cabrera",2008,88,8.9,258600.0,287.35,NaN

## 1.2 思路2：填充缺失值

In [5]:
# 1.查看数据
movie_df

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Proactive 5thgeneration infrastructure,Action,Gas modern statement production position class...,Ethan Oliver,"Kayla Graham, Austin Flores",2006,114,NaN,41007.0,696.77,42.9
1,2,Networked asymmetric middleware,Romance,Base describe voice especially fast lay art bl...,Cristina Garcia,"Kaitlyn Nelson, Kevin Shaw",1988,123,5.2,172732.0,NaN,64.1
2,3,Decentralized composite conglomeration,Comedy,Human born the. Field clear option artist gove...,Kevin Adams,"Daniel Guerra, Zachary Clark, Mark Lee",1984,80,8.0,950379.0,NaN,53.8
3,4,Secured global budgetary management,Drama,Present scene itself pass. Officer mission tra...,Deborah Hernandez,"Crystal Gonzalez, Nicole Vargas, Brandon Glass",2007,153,9.4,39528.0,685.14,58.5
4,5,Progressive 24hour migration,Adventure,Price authority nice quality. Help magazine ge...,Bryan Shaw,"Brandi Smith, Jeffrey Turner, Andrew Wilson, A...",2020,147,6.2,14157.0,343.83,78.3
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Automated holistic neural-net,Sci-Fi,Let market herself then start threat. Nation f...,Brittany Parrish,"Linda White, Sarah Foley",1994,80,9.3,915923.0,18.75,30.4
996,997,Distributed upward-trending attitude,Action,Back sell still green drive. Sound whether tea...,Cameron Mullins,"Charles Frost, Ashlee Wagner, Austin Rodriguez...",1983,171,8.8,589826.0,678.87,41.8
997,998,Pre-emptive zero tolerance intranet,Thriller,Film realize indeed land after to wide. Dark a...,Joshua Glover,"Jason Morales MD, Deanna Smith, Logan Hardy",1994,164,6.4,736854.0,112.06,22.3
998,999,Universal client-server moderator,Drama,Like probably shoulder other. Skill adult admi...,Robert Ramos,"Samantha Carlson, Sabrina Jones, Candace Walker",1990,103,8.0,898654.0,724.35,75.5
999,1000,Operative secondary toolset,Action,Professional most offer recent. Threat million...,Bruce Myers,"Frank Holmes, Samantha Cabrera",2008,88,8.9,258600.0,287.35,NaN

In [6]:
# 2.判断某列是否有缺失值
pd.isnull(movie_df) # 判断df对象的 每列的 每个值 是否为空（缺失值）
pd.notnull(movie_df) # 判断df对象的 每列的 每个值 是否不为空（非缺失值）

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,True,True,True,True,True,True,True,True,False,True,True,True
1,True,True,True,True,True,True,True,True,True,True,False,True
2,True,True,True,True,True,True,True,True,True,True,False,True
3,True,True,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...
995,True,True,True,True,True,True,True,True,True,True,True,True
996,True,True,True,True,True,True,True,True,True,True,True,True
997,True,True,True,True,True,True,True,True,True,True,True,True
998,True,True,True,True,True,True,True,True,True,True,True,True
999,True,True,True,True,True,True,True,True,True,True,True,False

In [7]:
# 3. 判断某列是否是 包含缺失值的列
np.all(pd.notnull(movie_df))

np.False_

In [8]:
# 4.填充缺失值
# 写法1：填充固定值
movie_df.fillna(888888).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Rank                1000 non-null   int64
 1   Title               1000 non-null   object
 2   Genre               1000 non-null   object
 3   Description         1000 non-null   object
 4   Director            1000 non-null   object
 5   Actors              1000 non-null   object
 6   Year                1000 non-null   int64
 7   Runtime (Minutes)   1000 non-null   int64
 8   Rating              1000 non-null   float64
 9   Votes               1000 non-null   float64
 10  Revenue (Millions)  1000 non-null   float64
 11  Metascore           1000 non-null   float64
dtypes: float64(4), int64(3), object(5)
memory usage: 93.9+ KB

In [9]:
# 写法2：填充 每列的平均值
movie_df['Votes'].fillna(movie_df['Votes'].mean(), inplace=True)
movie_df['Revenue (Millions)'].fillna(movie_df['Revenue (Millions)'].mean(), inplace=True)
movie_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Rank                1000 non-null   int64
 1   Title               1000 non-null   object
 2   Genre               1000 non-null   object
 3   Description         1000 non-null   object
 4   Director            1000 non-null   object
 5   Actors              1000 non-null   object
 6   Year                1000 non-null   int64
 7   Runtime (Minutes)   1000 non-null   int64
 8   Rating              856 non-null    float64
 9   Votes               1000 non-null   float64
 10  Revenue (Millions)  1000 non-null   float64
 11  Metascore           848 non-null    float64
dtypes: float64(4), int64(3), object(5)
memory usage: 93.9+ KB

C:\Users\Apr24\AppData\Local\Temp\ipykernel_15960\943651375.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  movie_df['Votes'].fillna(movie_df['Votes'].mean(), inplace=True)
C:\Users\Apr24\AppData\Local\Temp\ipykernel_15960\943651375.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  movie_df['Revenue (Millions)'].fillna(movie_df['Revenue (Millions)'].mean(), inplace=True)

In [10]:
# 5.for循环到的方式，使用 每列的平均值 来填充各列的缺失值
# 5.1 获取每个列名
for column in movie_df.columns:
    # 5.2 判断该列是否包含缺失值
    # movie_df[column] : 根据列名，找打df中的某一列 --> Series对象
    # pd.notnull(某列) ： 判断该列的每个值是否为非缺失值，True —> 不为空，False —> 为空（缺失值）
    # np.all() ： 判断所有元素是否为True
    if np.all(pd.notnull(movie_df[column])) == False:
        # 5.3 说明有缺失值
        print(column) # 输出列名
        # 5.4 获取该列的平均值
        mean_value = movie_df[column].mean()
        print(mean_value)
        # 5.5 用该列的平均值填充该列的缺失值
        movie_df[column].fillna(mean_value, inplace=True)

Rating
6.717640186915888
Metascore
59.42889150943397

C:\Users\Apr24\AppData\Local\Temp\ipykernel_15960\721416080.py:15: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  movie_df[column].fillna(mean_value, inplace=True)

In [11]:
# 6.查看处理后的结果
movie_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Rank                1000 non-null   int64
 1   Title               1000 non-null   object
 2   Genre               1000 non-null   object
 3   Description         1000 non-null   object
 4   Director            1000 non-null   object
 5   Actors              1000 non-null   object
 6   Year                1000 non-null   int64
 7   Runtime (Minutes)   1000 non-null   int64
 8   Rating              1000 non-null   float64
 9   Votes               1000 non-null   float64
 10  Revenue (Millions)  1000 non-null   float64
 11  Metascore           1000 non-null   float64
dtypes: float64(4), int64(3), object(5)
memory usage: 93.9+ KB

## 1.3 思路3：转换，然后填充缺失值或删除缺失值

In [12]:
#背景：实际开发中，不是所以有的缺失值都是用NaN来表示，例如：可能用 ？ 表示，如何删除这些缺失值
# 思路： 现先转换，后删除，即： ？ -> NaN -> 删除
# 1.加载数据
wis = pd.read_csv('./../Data/numeric_values.csv')
wis

    col_1 col_2 col_3 col_4 col_5 col_6 col_7 col_8 col_9 col_10 col_11 col_12
0     655   760   229   105   914   605     ?   239    28    734    559    460
1     829   778   715   285   981     ?   100   353     ?    471    997     81
2     850   907   592     ?   234    82     ?   285   855    380    687    960
3      74   176   251   389   948   571   333     ?     ?    324     68    966
4     736   672   906   470   143   575   765   920   371    142     94      ?
..    ...   ...   ...   ...   ...   ...   ...   ...   ...    ...    ...    ...
795   390   201     ?   345   778   342   442    17   106    141      ?    479
796   757   698   562   139   220     ?    12     ?   288    912      ?    946
797   122   257   550   961    46   284   674     ?   863    222    909     91
798   235     ?   714   366   570    28   643   684   177    240    751    848
799   136    63   232    33   935   376   902   855   158    854    486    176

[800 rows x 12 columns]

In [13]:
# 2.尝试删除缺失值
wis.dropna() # ? 不是缺失值 ，所有直接删不掉

    col_1 col_2 col_3 col_4 col_5 col_6 col_7 col_8 col_9 col_10 col_11 col_12
0     655   760   229   105   914   605     ?   239    28    734    559    460
1     829   778   715   285   981     ?   100   353     ?    471    997     81
2     850   907   592     ?   234    82     ?   285   855    380    687    960
3      74   176   251   389   948   571   333     ?     ?    324     68    966
4     736   672   906   470   143   575   765   920   371    142     94      ?
..    ...   ...   ...   ...   ...   ...   ...   ...   ...    ...    ...    ...
795   390   201     ?   345   778   342   442    17   106    141      ?    479
796   757   698   562   139   220     ?    12     ?   288    912      ?    946
797   122   257   550   961    46   284   674     ?   863    222    909     91
798   235     ?   714   366   570    28   643   684   177    240    751    848
799   136    63   232    33   935   376   902   855   158    854    486    176

[800 rows x 12 columns]

In [14]:
# 3. 解决上述的问题，? --> NaN --> 删除
wis.replace('?', np.nan).dropna()

    col_1 col_2 col_3 col_4 col_5 col_6 col_7 col_8 col_9 col_10 col_11 col_12
5     643   697    66   611   542   567    12   118   550    788    115    162
9     881   527   686   553   958   591   804   417   100    363    479     56
15    900   119   761   279   216   209   874   501   930     95    850      4
17     41   216   683   799   896   636   948   886   820    903    184    341
18    422   885   255   807   392   880   205   472   841    234    676    337
..    ...   ...   ...   ...   ...   ...   ...   ...   ...    ...    ...    ...
773   791   514   152   675   762   544   542   628   202    973     41    737
774   298   774   292   418   989   486   428   937   586    323    229    308
778   655   160   874   977   798   777   989   784   125    856    477    493
790   890   421   532   455   879   212   193   879   249    972     51    444
799   136    63   232    33   935   376   902   855   158    854    486    176

[182 rows x 12 columns]

# 2.数据合并

## 2.1 思路1：concat()，能行合并，还是列合并

In [15]:
# 1.准备数据
df = pd.read_csv('./../Data/全球GDP数据.csv', encoding='utf8')
df

df1 = df[:10]
df1

df2 = df[10:20]
df2

    year country           GDP
10  1961      中国   62716467625
11  1961      日本   47307342950
12  1961     加拿大   43461721692
13  1961     意大利   43385288344
14  1962      美国  583300000000
15  1962      英国   79233967692
16  1962      法国   68225478000
17  1962      中国   65716467625
18  1962      日本   50307342950
19  1962     加拿大   46461721692

In [16]:
# 2.通过 concat() 合并数据
#细节：列合并，默认参考 列名
new_df = pd.concat([df1, df2])  # 默认是列合并 axis=0，行合并：axis=1
new_df = pd.concat([df1, df2], axis=0)  # axis=0 是列合并，效果同上

#细节：行合并，默认参考 行索引（值）
new_df = pd.concat([df1, df2], axis=1)  # axis=1 是行合并 有空值是列索引不一致所造成的
new_df

      year country           GDP    year country           GDP
0   1960.0      美国  5.433000e+11     NaN     NaN           NaN
1   1960.0      英国  7.323397e+10     NaN     NaN           NaN
2   1960.0      法国  6.222548e+10     NaN     NaN           NaN
3   1960.0      中国  5.971647e+10     NaN     NaN           NaN
4   1960.0      日本  4.430734e+10     NaN     NaN           NaN
5   1960.0     加拿大  4.046172e+10     NaN     NaN           NaN
6   1960.0     意大利  4.038529e+10     NaN     NaN           NaN
7   1961.0      美国  5.633000e+11     NaN     NaN           NaN
8   1961.0      英国  7.623397e+10     NaN     NaN           NaN
9   1961.0      法国  6.522548e+10     NaN     NaN           NaN
10     NaN     NaN           NaN  1961.0      中国  6.271647e+10
11     NaN     NaN           NaN  1961.0      日本  4.730734e+10
12     NaN     NaN           NaN  1961.0     加拿大  4.346172e+10
13     NaN     NaN           NaN  1961.0     意大利  4.338529e+10
14     NaN     NaN           NaN  1962.0      美国  5.833000e+11
15     NaN     NaN           NaN  1962.0      英国  7.923397e+10
16     NaN     NaN           NaN  1962.0      法国  6.822548e+10
17     NaN     NaN           NaN  1962.0      中国  6.571647e+10
18     NaN     NaN           NaN  1962.0      日本  5.030734e+10
19     NaN     NaN           NaN  1962.0     加拿大  4.646172e+10

In [17]:
# 3.修改df2的列索引
df2.index = [0,1,2,3,4,10,11,12,13,14] # 修改列索引,使得前5行列索引一致，做试验
# 4.再次合并
new_df = pd.concat([df1, df2], axis=1)
new_df

      year country           GDP    year country           GDP
0   1960.0      美国  5.433000e+11  1961.0      中国  6.271647e+10
1   1960.0      英国  7.323397e+10  1961.0      日本  4.730734e+10
2   1960.0      法国  6.222548e+10  1961.0     加拿大  4.346172e+10
3   1960.0      中国  5.971647e+10  1961.0     意大利  4.338529e+10
4   1960.0      日本  4.430734e+10  1962.0      美国  5.833000e+11
5   1960.0     加拿大  4.046172e+10     NaN     NaN           NaN
6   1960.0     意大利  4.038529e+10     NaN     NaN           NaN
7   1961.0      美国  5.633000e+11     NaN     NaN           NaN
8   1961.0      英国  7.623397e+10     NaN     NaN           NaN
9   1961.0      法国  6.522548e+10     NaN     NaN           NaN
10     NaN     NaN           NaN  1962.0      英国  7.923397e+10
11     NaN     NaN           NaN  1962.0      法国  6.822548e+10
12     NaN     NaN           NaN  1962.0      中国  6.571647e+10
13     NaN     NaN           NaN  1962.0      日本  5.030734e+10
14     NaN     NaN           NaN  1962.0     加拿大  4.646172e+10

In [18]:
new_df = pd.concat([df1, df2], axis=1,join='outer') #默认是：满外连接，即：左表全集 + 右表全集 + 交集

new_df = pd.concat([df1, df2], axis=1,join='inner') # 指定为：内连接，即：只要交集

new_df

   year country           GDP  year country           GDP
0  1960      美国  543300000000  1961      中国   62716467625
1  1960      英国   73233967692  1961      日本   47307342950
2  1960      法国   62225478000  1961     加拿大   43461721692
3  1960      中国   59716467625  1961     意大利   43385288344
4  1960      日本   44307342950  1962      美国  583300000000

## 2.2 思路2：merge() --> 只能进行 行合并（水平合并）

In [19]:
# 准备数据集
df1 = pd.DataFrame({
    'key1': ['K0', 'K0', 'K1', 'K2'],
    'key2': ['K0', 'K1', 'K0', 'K1'],
    'A': ['A0', 'A1', 'A2', 'A3'],
    'B': ['B0', 'B1', 'B2', 'B3']
})

df2 = pd.DataFrame({
    'key1': ['K0', 'K1', 'K1', 'K2'],
    'key2': ['K0', 'K0', 'K0', 'K0'],
    'C': ['C0', 'C1', 'C2', 'C3'],
    'D': ['D0', 'D1', 'D2', 'D3']
})

# 2.查看数据
df1
df2

  key1 key2   C   D
0   K0   K0  C0  D0
1   K1   K0  C1  D1
2   K1   K0  C2  D2
3   K2   K0  C3  D3

In [20]:
# 3. 演示 merge()函数的 默认合并方式
pd.merge(df1, df2, how='inner',on=['key1', 'key2'])
pd.merge(df1, df2) # 效果同上，默认是 inner join 且参考同名列

  key1 key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K0  A2  B2  C1  D1
2   K1   K0  A2  B2  C2  D2

In [21]:
pd.merge(df1, df2, how='inner',on='key1')# 4.内连接，指定合并字段

  key1 key2_x   A   B key2_y   C   D
0   K0     K0  A0  B0     K0  C0  D0
1   K0     K1  A1  B1     K0  C0  D0
2   K1     K0  A2  B2     K0  C1  D1
3   K1     K0  A2  B2     K0  C2  D2
4   K2     K1  A3  B3     K0  C3  D3

In [22]:
# 5. 外连接，指定合并字段
pd.merge(df1,df2,how='outer',on=['key1','key2']) #  满外连接，关联字段为：key1、key2

  key1 key2    A    B    C    D
0   K0   K0   A0   B0   C0   D0
1   K0   K1   A1   B1  NaN  NaN
2   K1   K0   A2   B2   C1   D1
3   K1   K0   A2   B2   C2   D2
4   K2   K0  NaN  NaN   C3   D3
5   K2   K1   A3   B3  NaN  NaN

In [23]:
# 6.左外连接，指定合并字段   左表全集 + 交集
pd.merge(df1,df2,how='left',on=['key1','key2'])

# 回顾：concat() 写法： pd.concat([df1,df2,df3,...]) 可以拼接多个，技能合并行，也能合并列，不能指定合并字段，默认是外连接合并方式

  key1 key2   A   B    C    D
0   K0   K0  A0  B0   C0   D0
1   K0   K1  A1  B1  NaN  NaN
2   K1   K0  A2  B2   C1   D1
3   K1   K0  A2  B2   C2   D2
4   K2   K1  A3  B3  NaN  NaN

# 3. groupby()分组聚合 以及 分组过滤

In [24]:
# 1. 准备数据
df = pd.read_csv('./../Data/uniqlo.csv')
df

,store_id,city,channel,gender_group,age_group,wkd_ind,product,customer,revenue,order,quant,unit_cost
0,93810,上海,网购,女,青年,周末,运动户外,53,21911.43,44,70,133.53
1,13905,上海,网购,男,青年,周末,美妆护肤,102,76258.21,92,167,194.46
2,68878,西安,自提,男,中年,周末,运动户外,217,28952.88,88,72,236.11
3,54118,上海,网购,女,青年,周间,美妆护肤,136,8172.57,12,24,114.91
4,59615,上海,门店购买,女,中年,周间,美妆护肤,99,2555.92,91,18,52.31
...,...,...,...,...,...,...,...,...,...,...,...,...
1995,79776,成都,网购,女,中年,周间,食品生鲜,115,14439.81,105,198,41.86
1996,43888,杭州,自提,男,老年,周间,运动户外,91,21594.86,19,29,272.27
1997,93101,杭州,自提,男,青年,周末,食品生鲜,122,284.70,1,6,24.82
1998,92040,深圳,门店购买,女,青年,周末,食品生鲜,121,5577.96,45,72,25.17
1999,63717,南京,网购,男,中年,周末,运动户外,348,63049.29,33,59,379.34

## 3.1分组聚合

In [25]:
# agg -> Aggregate(聚合的意思)
# 格式：df.groupby(['分组字段1','分组字段2',...]).agg({'列名1':'聚合函数名','列名2','聚合函数名'})

In [26]:
# 1.场景1：按照单列分组
df.groupby(['city'])  # DataFrameGroupBy对象  -> DataFrame分组对象
df.groupby('city')    #细节：如果分组列只有一个，可以不加中括号

In [27]:
# 2.场景2：按照多列分组
df.groupby(['city','channel'])

In [28]:
# 3. 场景3：如何获取某个分组的数据
df.groupby(['city','channel']).get_group(('北京','门店购买'))

df.groupby(['city','channel']).get_group(('上海','网购'))

,store_id,city,channel,gender_group,age_group,wkd_ind,product,customer,revenue,order,quant,unit_cost
0,93810,上海,网购,女,青年,周末,运动户外,53,21911.43,44,70,133.53
1,13905,上海,网购,男,青年,周末,美妆护肤,102,76258.21,92,167,194.46
3,54118,上海,网购,女,青年,周间,美妆护肤,136,8172.57,12,24,114.91
5,47930,上海,网购,男,青年,周间,运动户外,428,28611.88,94,42,247.19
21,11934,上海,网购,男,青年,周间,服装鞋帽,443,2386.36,103,16,44.84
...,...,...,...,...,...,...,...,...,...,...,...,...
1811,27819,上海,网购,女,青年,周末,美妆护肤,125,60057.29,97,184,190.61
1832,56631,上海,网购,男,青年,周间,食品生鲜,440,4542.01,101,92,23.62
1845,17346,上海,网购,男,中年,周间,家居日用,88,133.71,31,2,34.43
1977,32042,上海,网购,男,中年,周间,运动户外,481,100782.53,191,76,540.76
1984,68414,上海,网购,男,青年,周间,运动户外,133,49533.18,85,129,181.24

In [29]:
# 4. 场景4：分组 + 聚合（聚合字段只有一个）
# 需求：根据 城市 和 渠道，对 销售金额 进行求和
# 写法1：通用版
df.groupby(['city','channel']).agg({'revenue':'sum'}) # DataFrame对象
# 写法2：简写版
df.groupby(['city','channel']).revenue.sum() #Series 对象

city  channel
上海    网购         1633490.02
      自提         2589864.89
      门店购买       4959977.83
北京    网购         9797800.11
      自提         3349387.25
      门店购买       5165698.74
南京    网购         6748468.04
      自提         4432630.60
      门店购买       6757769.01
广州    网购         6655420.53
      自提         6705438.93
      门店购买       6083416.60
成都    网购         5514940.29
      自提         6423781.86
      门店购买       5698482.29
杭州    网购         6270124.50
      自提         7218039.41
      门店购买       8714223.10
武汉    网购         7436696.52
      自提         4430439.05
      门店购买       3584200.74
深圳    网购         6382817.84
      自提         4150260.27
      门店购买       5182010.50
西安    网购         7990875.88
      自提         4553763.77
      门店购买       5150223.92
重庆    网购         3600214.74
      自提         4656177.03
      门店购买       3998104.72
Name: revenue, dtype: float64

In [39]:
# 5.场景5： 分组 + 聚合（聚合字段有两个，聚合字段相同）
# 需求：根据城市 和 销售渠道分组，计算：销售金额,订单数量  总和
# 写法1：通用版
df.groupby(['city','channel']).agg({'revenue':'sum','order':'sum'})

# 写法2：变形版
df.groupby(['city','channel'])[['revenue','order']].sum()

                 revenue  order
city channel
上海   网购       1633490.02   5366
     自提       2589864.89   4490
     门店购买     4959977.83   4875
北京   网购       9797800.11   6199
     自提       3349387.25   5633
     门店购买     5165698.74   4464
南京   网购       6748468.04   6408
     自提       4432630.60   5919
     门店购买     6757769.01   6529
广州   网购       6655420.53   5539
     自提       6705438.93   6265
     门店购买     6083416.60   6324
成都   网购       5514940.29   4681
     自提       6423781.86   5653
     门店购买     5698482.29   6342
杭州   网购       6270124.50   6374
     自提       7218039.41   4358
     门店购买     8714223.10   6433
武汉   网购       7436696.52   5915
     自提       4430439.05   4858
     门店购买     3584200.74   4736
深圳   网购       6382817.84   4804
     自提       4150260.27   5025
     门店购买     5182010.50   4002
西安   网购       7990875.88   5646
     自提       4553763.77   4185
     门店购买     5150223.92   5510
重庆   网购       3600214.74   5909
     自提       4656177.03   3714
     门店购买     3998104.72   4180

In [45]:
# 6.场景6： 分组 + 聚合（聚合字段有两个，聚合字段不同）
# 需求：根据城市 和 销售渠道分组，分别计算：销售金额的平均值，成本的总和
df.groupby(['city','channel']).agg({'revenue':'mean','unit_cost':'sum'})

                    revenue  unit_cost
city channel
上海   网购        25523.281563   14465.41
     自提        42456.801475   27058.66
     门店购买      78729.806825   27030.17
北京   网购       132402.704189   46245.28
     自提        49990.854478   19631.48
     门店购买      99340.360385   25819.50
南京   网购        87642.442078   41605.79
     自提        58324.086842   36381.33
     门店购买      87763.233896   28369.01
广州   网购        83192.756625   29358.45
     自提        93131.096250   35971.63
     门店购买      81112.221333   37141.68
成都   网购        98481.076607   22954.99
     自提        86807.862973   38686.25
     门店购买      74980.030132   43474.33
杭州   网购        97970.695312   32274.12
     自提       111046.760154   31978.91
     门店购买     108927.788750   48185.66
武汉   网购       107778.210435   30587.77
     自提        64209.261594   23526.00
     门店购买      61796.564483   26674.55
深圳   网购       101314.568889   23886.03
     自提        66939.681774   24954.68
     门店购买      90912.464912   27648.78
西安   网购       126839.299683   41675.16
     自提        87572.380192   26078.90
     门店购买      73574.627429   30024.67
重庆   网购        57146.265714   18848.82
     自提        81687.316316   31497.64
     门店购买      62470.386250   38318.46

## 3.2 分组过滤.

In [62]:
# 需求：按照城市分组，查询每组销售金额平均值 大于200的全部数据
# 即：算出每组的销售金额，找出金额大于200的的组，然后显示这些组所有数据

# 1.根据城市分组，计算每个城市的销售金额的 平均值
df.groupby(['city']).revenue.mean()

# 2. 根据城市分组，查看上海分组的数据
df.groupby(['city']).get_group('上海')

# 3. 完成需求
df.groupby(['city']).filter(lambda x:x.revenue.mean()>90000)
df.groupby(['city']).revenue.filter(lambda x:x.mean()>90000)

C:\Users\Apr24\AppData\Local\Temp\ipykernel_15960\2389502584.py:8: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  df.groupby(['city']).get_group('上海')

2        28952.88
13         576.56
17       26040.38
18        2871.46
19      124646.44
          ...
1987      3354.73
1992      9040.43
1993      9393.14
1996     21594.86
1997       284.70
Name: revenue, Length: 587, dtype: float64

# 4. 交叉表（了解） 和 透视表（掌握）

In [68]:
# 1. 交叉表演示：
# 创建一个示例数据
data = {
    '性别': ['男', '女', '男', '女','女','男', '女', '男'],
    '购买': ['是', '否', '是', '是', '否', '是', '是', '否'],
}

df = pd.DataFrame(data)

# 2. 交叉表
crosstab = pd.crosstab(df['性别'], df['购买'])
print(crosstab)

购买  否  是
性别
女   2  2
男   1  3

In [74]:
# 2.透视表
data = {
    '性别': ['男', '女', '男', '女','女','男', '女', '男'],
    '购买': ['是', '否', '是', '是', '否', '是', '是', '否'],
    '金额':[100,120,150,180,90,120,150,180]
}

df = pd.DataFrame(data)

df.pivot_table(index='性别', columns='购买', values='金额', aggfunc='mean')

购买      否           是
性别
女   105.0  165.000000
男   180.0  123.333333

In [82]:
 # 3. 透视表案例：
 #3.1 准备数据
df = pd.read_csv('./../Data/uniqlo.csv')
df

# 3.2  需求：根据城市， 销售渠道分组，计算 销售金额  总和
df.groupby(['city','channel']).agg({'revenue':'sum'})
# df.groupby(['city','channel'],as_index=False).agg({'revenue':'sum'}) #不把分组字段当做行索引，而是当做列

# 写法2：pivot_table()透视表
df.pivot_table(index='city',columns='channel',values='revenue',aggfunc='sum')

channel          网购          自提        门店购买
city
上海       1633490.02  2589864.89  4959977.83
北京       9797800.11  3349387.25  5165698.74
南京       6748468.04  4432630.60  6757769.01
广州       6655420.53  6705438.93  6083416.60
成都       5514940.29  6423781.86  5698482.29
杭州       6270124.50  7218039.41  8714223.10
武汉       7436696.52  4430439.05  3584200.74
深圳       6382817.84  4150260.27  5182010.50
西安       7990875.88  4553763.77  5150223.92
重庆       3600214.74  4656177.03  3998104.72